server:
    port: 8093

spring:
    datasource:
        url: jdbc:postgresql://localhost:${configurations.port}/${configurations.database}
        driver-class-name: org.postgresql.Driver
        username: ${configurations.username}
        password: ${configurations.password}
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
    liquibase:
        change-log: db/changeLog.xml
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        open-in-view: false
    kafka:
        consumer:
            bootstrap-servers: localhost:9092
            group-id: myGroup
            auto-offset-reset: earliest
io:
    reflectoring:
        kafka:
            bootstrap-servers: localhost:9092

configurations:
    port: 5439
    database: message_db
    username: postgres
    password: postgres